<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>gov.portal</groupId>
  <artifactId>payments</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <version>1.60</version>
    </dependency>
  </dependencies>
</project>
