"""`python -m mox make-demo` - builds the synthetic 'gov-portal-legacy' app covering all 7 planes.
Keys are generated fresh on every run; nothing here is a real credential."""
import io
import json
import shutil
import tarfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization as ser
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.hazmat.primitives.serialization import pkcs12
from cryptography.x509.oid import NameOID

P12_PASSWORD = b"changeit"  # synthetic demo password

FILES = {
    "README.md": "# gov-portal-legacy (SYNTHETIC DEMO TARGET)\n\nGenerated by `python -m mox make-demo`. "
                 "Everything here is synthetic and safe. `vendor/sync-agent.bin` is NOT a real binary: "
                 "it is a blob containing marker strings for the scanner.\n",
    "auth/token_signer.py": '''from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding

KEY_PATH = "certs/api-gw.key"


def sign(payload: bytes) -> bytes:
    with open(KEY_PATH, "rb") as f:
        key = serialization.load_pem_private_key(f.read(), password=None)
    return key.sign(payload, padding.PKCS1v15(), hashes.SHA256())
''',
    "auth/passwords.py": '''import hashlib


def hash_password(pw: str) -> str:
    return hashlib.md5(pw.encode()).hexdigest()
''',
    "payments/Crypto.java": '''import java.security.*;
import javax.crypto.Cipher;

public class Crypto {
    static byte[] digest(byte[] data) throws Exception {
        return MessageDigest.getInstance("SHA-1").digest(data);
    }

    static KeyPair newKey() throws Exception {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
        kpg.initialize(2048);
        return kpg.generateKeyPair();
    }

    static Cipher legacyCipher() throws Exception {
        return Cipher.getInstance("DES/CBC/PKCS5Padding");
    }
}
''',
    "web/sign.js": '''const crypto = require('crypto');

function fingerprint(s) {
  return crypto.createHash('md5').update(s).digest('hex');
}

function sign(data, pem) {
  const signer = crypto.createSign('RSA-SHA256');
  signer.update(data);
  return signer.sign(pem, 'base64');
}

module.exports = { fingerprint, sign };
''',
    "utils/legacy_aes.py": '''from Crypto.Cipher import AES


def encrypt_blob(key: bytes, blob: bytes) -> bytes:
    cipher = AES.new(key, AES.MODE_ECB)
    return cipher.encrypt(blob)
''',
    "services/ecdsa.go": '''package services

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
)

func NewSigningKey() (*ecdsa.PrivateKey, error) {
	return ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
}
''',
    "requirements.txt": "pycryptodome==3.9.0\ncryptography==2.9\nflask==1.1.2\n",
    "package.json": json.dumps({"name": "gov-portal-web", "version": "1.0.0",
                                "dependencies": {"node-forge": "0.9.1", "jsonwebtoken": "8.5.1",
                                                 "express": "4.17.1"}}, indent=2) + "\n",
    "pom.xml": '''<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>gov.portal</groupId>
  <artifactId>payments</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <version>1.60</version>
    </dependency>
  </dependencies>
</project>
''',
    "conf/nginx.conf": '''server {
    listen 443 ssl;
    server_name portal.gov-portal.local;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:AES128-SHA:DES-CBC3-SHA;
    ssl_certificate certs/api-gw.crt;
    ssl_certificate_key certs/api-gw.key;
}
''',
    "conf/nginx-edge.conf": '''server {
    listen 8443 ssl;
    server_name edge.gov-portal.local;
    ssl_protocols TLSv1.3;
    ssl_ecdh_curve X25519MLKEM768:X25519;
    ssl_certificate certs/ecdsa-p256.crt;
    ssl_certificate_key certs/ecdsa-p256.key;
}
''',
    "conf/java.security": "# demo JVM security overrides\njdk.tls.disabledAlgorithms=SSLv3, MD5withRSA\n"
                          "jdk.tls.legacyAlgorithms=DES, DESede, RC4\n",
    "infra/kms.tf": 'resource "aws_kms_key" "portal_signing" {\n  description = "portal signing key"\n'
                    '  key_usage   = "SIGN_VERIFY"\n  key_spec    = "RSA_2048"\n}\n',
    "Dockerfile": "FROM debian:9\nRUN apt-get update && apt-get install -y openssl=1.1.1k-1 curl\n"
                  "COPY certs/api-gw.crt /app/certs/api-gw.crt\n",
}


def _name(cn: str) -> x509.Name:
    return x509.Name([x509.NameAttribute(NameOID.ORGANIZATION_NAME, "gov-portal-legacy (demo)"),
                      x509.NameAttribute(NameOID.COMMON_NAME, cn)])


def _cert(key, cn, days=365, start_days_ago=30, sig=hashes.SHA256(), issuer=None, issuer_key=None):
    now = datetime.now(timezone.utc)
    b = (x509.CertificateBuilder().subject_name(_name(cn)).issuer_name(issuer or _name(cn))
         .public_key(key.public_key()).serial_number(x509.random_serial_number())
         .not_valid_before(now - timedelta(days=start_days_ago))
         .not_valid_after(now - timedelta(days=start_days_ago) + timedelta(days=days)))
    return b.sign(issuer_key or key, sig)


def _pem_cert(c) -> bytes:
    return c.public_bytes(ser.Encoding.PEM)


def _pem_key(k) -> bytes:
    return k.private_bytes(ser.Encoding.PEM, ser.PrivateFormat.TraditionalOpenSSL, ser.NoEncryption())


def _docker_image(cert_pem: bytes) -> bytes:
    layer = io.BytesIO()
    with tarfile.open(fileobj=layer, mode="w") as lt:
        info = tarfile.TarInfo("app/certs/api-gw.crt")
        info.size = len(cert_pem)
        lt.addfile(info, io.BytesIO(cert_pem))
    parts = {"manifest.json": json.dumps([{"Config": "config.json", "RepoTags": ["gov-portal:legacy"],
                                           "Layers": ["a1b2c3/layer.tar"]}]).encode(),
             "config.json": b'{"architecture":"amd64","os":"linux"}',
             "a1b2c3/layer.tar": layer.getvalue()}
    out = io.BytesIO()
    with tarfile.open(fileobj=out, mode="w") as t:
        for name, data in parts.items():
            info = tarfile.TarInfo(name)
            info.size = len(data)
            t.addfile(info, io.BytesIO(data))
    return out.getvalue()


def build(out: Path) -> Path:
    out = Path(out)
    if out.exists():
        shutil.rmtree(out)
    for rel, text in FILES.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8", newline="\n")

    def put(rel: str, data: bytes):
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)

    gw_key = rsa.generate_private_key(65537, 2048)
    gw_cert = _cert(gw_key, "api-gw.gov-portal.local")
    put("certs/api-gw.key", _pem_key(gw_key))
    put("certs/api-gw.crt", _pem_cert(gw_cert))
    # the SAME api-gw key also lives inside the app keystore
    put("keystore/app.p12", pkcs12.serialize_key_and_certificates(
        b"api-gw", gw_key, gw_cert, None, ser.BestAvailableEncryption(P12_PASSWORD)))
    ca_key = rsa.generate_private_key(65537, 4096)
    put("certs/internal-ca.crt", _pem_cert(_cert(ca_key, "internal-ca", days=3650)))
    legacy_key = rsa.generate_private_key(65537, 1024)
    put("certs/legacy-portal.crt", _pem_cert(_cert(legacy_key, "legacy-portal", days=365, start_days_ago=2000)))  # expired
    ec_key = ec.generate_private_key(ec.SECP256R1())
    put("certs/ecdsa-p256.crt", _pem_cert(_cert(ec_key, "edge.gov-portal.local")))
    put("vendor/sync-agent.bin", b"\x7fELF\x02\x01\x01\x00" + b"\x00" * 24 + b"SYNTHETIC-DEMO-BLOB\x00" +
        b"OpenSSL 1.1.1k  25 Mar 2021\x00RSA_generate_key\x00MD5_Init\x00" + b"\x00" * 16)
    put("image/app-image.tar", _docker_image(_pem_cert(gw_cert)))
    return out
